Make basket
Marcin-sys/SimpleShop pull request #1
Opened 2021-11-30 18:17 UTC by Marcin-sys

Created request

2021-11-30 19:22 UTC, KrzysztofM01 requested changes
Added comments

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +            choiceEntry = sc.nextInt();
user can type in string, float or anything else and break the program, add a safeguard against it

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +                    new Menu().menu();
you keep creating new menu object each time there is a human interaction, this is not optimal. It would be easier if you just passed `Menu` class as a variable for this class and re-use it here

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +                    for (Products products : productsArrayList) products.print();
can be simplified with java streams to: `productsArrayList.forEach(Products::print);`

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/ProductList.java
> +    public ArrayList<Products> makeProductList(){
don't return `ArrayList` but `List` - https://stackoverflow.com/questions/10328658/should-i-return-list-or-arraylist
`It's best to return the most generic type that's appropriate for your interface. `

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +public class Products {
Why plural form? This fits more to `Product` which is singular and suggest one item.

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +        id = productIdentifier;
in constructor always add `this` before assigning values, so:
`this.id = productIdentifier`
Since the class name is `Product` there is no need to prefix the constructor's parameters with `product`, just go with `id, price, name`

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +    private final Integer id;
Why are you using boxed integer instead of primitive one?

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +        System.out.println("Lp: "+id+" - Name of product: " + name +" - Price: "+ price + " PLN");
According to Single responsibility principle, class should have only one purpose - this class should be a holder of product information. You should add here a method to print stuff, instead whereever you want to print it, use this class `toString()` method to change it to string

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +public class Products {
This class can be simplified to:
```
@Value
public class Product {
    int id;
    float price;
    String name;
}
```
with lombok, or with Java 17+ to record:
```
public record Product(int id, float price, String name) {
}
```

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +                    new Menu().menu();
same goes for other objects (`AddNewProduct`, `RemoveProduct`, PayForBasker`), ask yourself a question do you need to create a new object each time

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +    int choiceEntry = -1;
why is this a class variable instead of local variable? It's also not private, so users of this class could modify this value in mid call of `chooseNumberFromMenu` to modify it and completly break the logic

2021-11-30 19:22 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +    public Factory() {
There is no need to create empty public constructor, java does that by default if there is no constructor present

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/basket/PayForBasket.java
> +public class PayForBasket {
Why `PayForBasket` class has `showWhatInsideBasket()` method? Either remove the method or change the class name, as it is right now it makes little sense. I could suggest `BasketOperations` or something like that if you want to have more methods inside

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/Main.java
> +        new Menu().MenuPrinter();
result of this is not used anywhere

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/basket/factory/FactoryMenageShopping.java
> +public class FactoryMenageShopping {
typo mistake should be - `FactoryManageShopping`, but still think about the name of the class. Is this really a factory? Do we create anything here? Think about another possible names, think what this class does and name it accordingly to what it's responsible for, to what it does

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/basket/factory/FactoryMenageShopping.java
> +                        System.out.println(menu);
if you wanted to print menu here, this won't work, this won't return the string 
```
"""
                Please choose number from menu again.
                1. Check all product's
                2. Add new product to basket
                3. Remove product from basket
                4. Check what is inside basket
                5. Pay for all product inside basket
                6. End shopping"""
```
but something like "Menu@5314fdeas21" which is object reference. When you use `System.out.println(object)` on some object, it will use the object's `toString()` method. You haven't overriden that method in your class definition, so by default it will print the reference name of the object.

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/products/Products.java
> +    public Integer getId() {
no need to add getters for `record`, they will be automatically generated

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/menu/Menu.java
> +public class Menu {
still not resolved

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/products/ProductList.java
> +    public ArrayList<Products> makeProductList(){
still not resolved

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/basket/factory/FactoryMenageShopping.java
> +            Scanner sc = new Scanner(System.in);
scanner is still not closed, if you are using some close'able resource the syntax is:
```
try( Scanner sc = new Scanner(System.in)) {
   ... code here ...
} catch (Exception e) {
   ... exception handling here ...
}

```

2021-12-18 12:13 UTC, KrzysztofM01 commented on src/main/java/basket/factory/Factory.java
> +            choiceEntry = sc.nextInt();
still not resolved

2021-12-18 15:06 UTC, Marcin-sys commented on src/main/java/menu/Menu.java
> +public class Menu {
Done

2021-12-18 15:20 UTC, Marcin-sys commented on src/main/java/basket/factory/Factory.java
> +        Scanner sc = new Scanner(System.in);
why?

2021-12-18 15:21 UTC, Marcin-sys commented on src/main/java/basket/factory/Factory.java
> +public class Factory {
Done

2021-12-18 15:21 UTC, Marcin-sys commented on src/main/java/basket/factory/Factory.java
> +            choiceEntry = sc.nextInt();
Done

2021-12-27 18:42 UTC, Marcin-sys commented on src/main/java/products/Products.java
> +    private final Integer id;
Done

2021-12-27 18:42 UTC, Marcin-sys commented on src/main/java/products/Products.java
> +        System.out.println("Lp: "+id+" - Name of product: " + name +" - Price: "+ price + " PLN");
Done

2021-12-27 18:42 UTC, Marcin-sys commented on src/main/java/products/Products.java
> +public class Products {
Done

2021-12-27 18:43 UTC, Marcin-sys commented on src/main/java/basket/factory/Factory.java
> +    int choiceEntry = -1;
Done

2021-12-27 18:43 UTC, Marcin-sys commented on src/main/java/basket/factory/Factory.java
> +    public Factory() {
Done

2021-12-27 18:46 UTC, Marcin-sys commented on src/main/java/Main.java
> +        new Menu().MenuPrinter();
Done

2021-12-27 18:47 UTC, Marcin-sys commented on src/main/java/basket/factory/FactoryMenageShopping.java
> +public class FactoryMenageShopping {
Done

2021-12-27 18:50 UTC, Marcin-sys commented on src/main/java/basket/factory/FactoryMenageShopping.java
> +                        System.out.println(menu);
Done 
String menu = new Menu().returnMenuListInString();

2021-12-27 18:53 UTC, Marcin-sys commented on src/main/java/products/Products.java
> +    public Integer getId() {
Done

2022-01-07 13:43 UTC, Marcin-sys commented
DONE

2022-01-08 10:45 UTC, KrzysztofM01 requested changes

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/products/ProductList.java
> +public class ProductList {
the class should reflect what it's doing. The purpose of this class is to create product list, so change the class name to reflect it - i.e. `ProductListProvider`

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/products/ProductList.java
> +        productList.add(new Product(0,"gruszka",12));
Use only english in your code

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/products/ProductList.java
> +        ArrayList<Product> productList = new ArrayList<>();
if you are instantiating a new object, don't assign it to super type if you aren't going to use methods from it. You should always hide the implementation, so instead assign:
`List<Product> productList = new ArrayList<>();`
More to read about it: https://www.baeldung.com/java-liskov-substitution-principle

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/menu/Menu.java
> +    public String printMainMenu(){
this method does not print anything. It returns current mainMenu. Previously it was printing something, now it doesn't so please change the method name to something more descriptive of it's result.

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/basket/Basket.java
> +    List<Product> listOfProducts = new ProductList().makeProductList();
you are using this list like map, so instead of using list to do map's job, change it to `Map<Integer, Product>`

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/basket/Basket.java
> +    }
you can use java stream to simplify this:
```
double price = basketList.stream().mapToDouble(Product::price).sum();
...
```

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/basket/factory/ShopManager.java
> +public class ShopManager {
When you have a class named `SomethingManager` it's an indicator that this class is written poorly, because you can't name what exactly this class is responsible for. Which is correct in this case because this class is responsible for far too many things. 

I would recommend moving out of this class few things:
- class responsible for taking user's input and validating if it's correct `UserInputProvider`
- class that takes int input and basing on it makes a decision what to do `ShopService`
- class that wraps it all together in a simple while loop executing one then another thing in it, meaning that it will use 1st class to take input, then it will pass it to 2nd to execute what needs to be done `ShoppingJourney`

2022-01-08 10:45 UTC, KrzysztofM01 commented on src/main/java/basket/factory/ShopManager.java
> +                        productId = getValidIntInput(0, productListSize, sc);
this is invalid. the method `getValidIntInput` takes min and max which are inclusive range - meaning that if the productListSize is equal to 4, the method will accept those ints: `{0, 1, 2, 3, 4}`. If you pass in there 4, it will throw exception because there is no product with id 4.
You need to input to that method a proper max that will take this into consideration

2022-01-26 19:21 UTC, closed without merging